options:
  bounce_address:
    type: string
    description: Envelope sender address for outgoing email.
    default: "noreply@launchpad.test"
  bzr_imports_root_url:
    type: string
    description: >
      Internal URL prefix for Bazaar branches imported from other revision
      control systems, used by the branch puller.
    default:
  bzr_lp_prefix:
    type: string
    description: >
      URL prefix used to address Bazaar branches on this instance.
    default: lp://dev/
  bzr_lp_url_hosts:
    type: string
    description: >
      Comma-separated list of hosts which may be used to refer to this
      server's branches in "lp:" URLs.
    default: dev
  candid_service_root:
    type: string
    description: >
      URL to the Candid service, used to discharge certain kinds of
      macaroons.
    default:
  charmhub_secrets_public_key:
    type: string
    description: >
      Base64-encoded NaCl public key for encrypting Charmhub upload tokens.
    default:
  charmhub_storage_url:
    type: string
    description: Charmhub's storage URL endpoint.
    default:
  charmhub_url:
    type: string
    description: Charmhub's primary URL endpoint.
    default:
  cron_control_url:
    type: string
    description: URL of file used to control whether cron scripts run.
    default: "file:cronscripts.ini"
  databases:
    type: string
    description: >
      YAML-encoded information about database relations, overriding the
      defaults.  For example, setting this to "db: {name: launchpad_prod}"
      changes the name of the database used by the "db" relation.
    default: ""
  db_statement_timeout:
    type: int
    description: SQL statement timeout in milliseconds.
    default:
  default_batch_size:
    type: int
    description: The default size used in a batched listing of results.
    default: 50
  domain:
    type: string
    description: Domain name for this instance.
    default: "launchpad.test"
  domain_bzr:
    type: string
    description: Domain name for this instance's Bazaar service, if any.
    default:
  domain_git:
    type: string
    description: Domain name for this instance's Git service, if any.
    default:
  domain_lists:
    type: string
    description: >
      Domain name for this instance's mailing list service, if any.
    default:
  domain_xmlrpc_private:
    type: string
    description: Domain name for this instance's private XML-RPC service.
    default: "xmlrpc-private.launchpad.test"
  geoip_database:
    type: string
    description: >
      The database used by our GeoIP library.  Only GeoIP2/GeoLite2 Country
      databases are supported.
    default:
  git_loose_objects_threshold:
    type: int
    description: >
      Threshold for the number of loose objects that triggers automatic
      repacking of Git repositories.
    default:
  git_packs_threshold:
    type: int
    description: >
      Threshold for the number of pack files that triggers automatic
      repacking of Git repositories.
    default:
  gpg_upload_keys:
    type: boolean
    description: Should we allow uploading keys to the keyserver?
    default: false
  is_demo:
    type: boolean
    description: >
      Should pages be styled to indicate the use of a demo system?
    default: true
  http_proxy:
    type: string
    description: Proxy to be used when issuing HTTP requests.
    default:
  internal_bzr_api_endpoint:
    type: string
    description: The URL of the internal Bazaar hosting API endpoint.
    default:
  librarian_download_host:
    type: string
    description: Host the Librarian is listening on for HTTP requests.
    default:
  librarian_download_port:
    type: int
    description: >
      Port number the Librarian listens for HTTP GET and HEAD requests on.
    default:
  librarian_download_url:
    type: string
    description: The base URL used to generate URLs to the Library contents.
    default:
  librarian_restricted_download_host:
    type: string
    description: >
      Host the Restricted Librarian is listening on for HTTP requests.
    default:
  librarian_restricted_download_port:
    type: int
    description: >
      Port number the Restricted Librarian listens for HTTP GET and HEAD
      requests on.
    default:
  librarian_restricted_download_url:
    type: string
    description: >
      The base URL used to generate URLs to the Restricted Library contents.
    default:
  librarian_restricted_upload_host:
    type: string
    description: >
      Host the Restricted Librarian is listening on for storage requests.
    default:
  librarian_restricted_upload_port:
    type: int
    description: >
      Port number the Restricted Librarian listens for storage requests on.
    default:
  librarian_upload_host:
    type: string
    description: Host the Librarian is listening on for storage requests.
    default:
  librarian_upload_port:
    type: int
    description: >
      Port number the Librarian listens for storage requests on.
    default:
  log_hosts_allow:
    type: string
    description: >
      Hosts that should be allowed to rsync logs.  Note that this relies on
      the nrpe subordinate charm to set up /etc/rsyncd.conf properly.
    default: ""
  mailman_shared_secret:
    type: string
    description: >
      Shared secret used to pre-approve Launchpad-generated messages to
      Launchpad mailing lists.
    default:
  oci_registry_credentials_public_key:
    type: string
    description: >
      Base64-encoded NaCl public key for encrypting OCI registry upload
      credentials.
    default:
  oops_prefix:
    type: string
    description: A prefix for OOPS codes for this instance.
    default: "TEST"
  openid_alternate_provider_roots:
    type: string
    description: >
      Comma-separated list of additional URLs to recognise as valid prefixes
      for our accounts' OpenID identifiers.
    default:
  openid_provider_root:
    type: string
    description: URL to the OpenID provider to authenticate against.
    default: https://testopenid.test/
  port_xmlrpc:
    type: int
    description: Port for the XML-RPC application server.
    default: 8087
  ppa_base_url:
    type: string
    description: External base URL for PPAs.
    default: http://ppa.launchpad.test/
  ppa_private_base_url:
    type: string
    description: External base URL for private PPAs.
    default: http://private-ppa.launchpad.test/
  session_cookie_name:
    type: string
    description: The ID of the cookie used to store the session token.
    default: launchpad_dev
  site_message:
    type: string
    description: >
      If provided, this message will appear in the site status bar at the
      top of every page.
    default:
  snap_store_secrets_public_key:
    type: string
    description: >
      Base64-encoded NaCl public key for encrypting snap store upload
      tokens.
    default:
  snap_store_upload_url:
    type: string
    description: The snap store's upload URL endpoint.
    default:
  snap_store_url:
    type: string
    description: The snap store's primary URL endpoint.
    default:
  soft_request_timeout:
    type: int
    description: Soft request timeout in milliseconds.
    default:
  statsd_environment:
    type: string
    description: Statsd environment name.
    default:
  ubuntu_disable_filebug:
    type: boolean
    description: Should +filebug be disabled for Ubuntu?
    default: false
  uploader_default_recipient:
    type: string
    description: Default email recipient for package upload notifications.
    default:
  uploader_default_sender:
    type: string
    description: Default email sender for package upload notifications.
    default:
  webhooks_proxy_url:
    type: string
    description: Outbound webhook request proxy URL.
    default:
  # layer-apt
  install_sources:
    default: |
      - ppa:launchpad/ppa
  install_keys:
    default: |
      - null  # PPA keys securely added via Launchpad.
