# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-json
        exclude: |
          (?x)^(
            lib/lp/services/sitesearch/tests/data/bingsearchservice-incomplete-response\.json
          )$
    -   id: check-xml
        exclude: |
          (?x)^(
            lib/lp/bugs/tests/testfiles/broken_bug_li_item\.xml|
            lib/lp/bugs/tests/testfiles/unescaped_control_character.xml
          )$
    -   id: check-yaml
    -   id: debug-statements
        exclude: systemdocs\.py
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, db-devel]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--keep-percent-format, --py3-plus]
        exclude: |
          (?x)^(
            lib/contrib/.*
            |lib/devscripts/.*
            |utilities/community-contributions\.py
            |utilities/update-sourcecode
          )$
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: |
          (?x)^lib/lp/(
            answers
            |app
            |archivepublisher
            |archiveuploader
          )/
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
    -   id: isort
        name: isort (old-style)
        args:
        -   --combine-as
        -   --force-grid-wrap=2
        -   --force-sort-within-sections
        -   --trailing-comma
        -   --line-length=78
        -   --lines-after-imports=2
        -   --multi-line=8
        -   --dont-order-by-type
        exclude: |
          (?x)^lib/lp/(
            answers
            |app
            |archivepublisher
            |archiveuploader
          )/
    -   id: isort
        alias: isort-black
        name: isort (black)
        args: [--profile, black]
        files: |
          (?x)^lib/lp/(
            answers
            |app
            |archivepublisher
            |archiveuploader
          )/
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: ^lib/contrib/
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v4.2.0
    hooks:
    -   id: eslint
        args: [--quiet]
-   repo: https://git.launchpad.net/lp-lint-doctest
    rev: '0.4'
    hooks:
    -   id: lp-lint-doctest
        args: [--allow-option-flag, IGNORE_EXCEPTION_MODULE_IN_PYTHON2]
        exclude: ^doc/.*
