# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-json
        exclude: |
          (?x)^(
            lib/lp/services/sitesearch/tests/data/bingsearchservice-incomplete-response\.json
          )$
    -   id: check-xml
        exclude: |
          (?x)^(
            lib/lp/bugs/tests/testfiles/broken_bug_li_item\.xml|
            lib/lp/bugs/tests/testfiles/unescaped_control_character.xml
          )$
    -   id: check-yaml
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, db-devel]
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: ^lib/contrib/
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v4.2.0
    hooks:
    -   id: eslint
        args: [--quiet]
