# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-json
        exclude: |
          (?x)^(
            lib/lp/services/sitesearch/tests/data/bingsearchservice-incomplete-response\.json
          )$
    -   id: check-xml
        exclude: |
          (?x)^(
            lib/lp/bugs/tests/testfiles/broken_bug_li_item\.xml|
            lib/lp/bugs/tests/testfiles/unescaped_control_character.xml
          )$
    -   id: check-yaml
    -   id: debug-statements
        exclude: systemdocs\.py
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, db-devel]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--keep-percent-format]
        exclude: |
          (?x)^(
            lib/contrib/.*
            |utilities/community-contributions\.py
          )$
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: |
          (?x)^(
            lib/contrib/.*
            |utilities/community-contributions\.py
          )$
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
    -   id: isort
        name: isort
        args: [--profile, black]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        exclude: ^lib/contrib/
        additional_dependencies:
          - flake8-absolute-import==1.0.0.1
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.31.0
    hooks:
    -   id: eslint
        args: [--quiet]
-   repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
    -   id: blackdoc
        args: ["-l", "78"]
        exclude: ^doc/.*
-   repo: https://git.launchpad.net/lp-lint-doctest
    rev: '0.5'
    hooks:
    -   id: lp-lint-doctest
        args: [--allow-option-flag, IGNORE_EXCEPTION_MODULE_IN_PYTHON2]
        exclude: ^doc/.*
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
    -   id: shellcheck
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell
        files: ^doc/.*\.rst$
-   repo: https://github.com/get-woke/woke
    rev: v0.19.0
    hooks:
    -   id: woke-from-source
        files: ^doc/.*\.rst$
