# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-json
        exclude: |
          (?x)^(
            lib/lp/services/sitesearch/tests/data/bingsearchservice-incomplete-response\.json
          )$
    -   id: check-xml
        exclude: |
          (?x)^(
            lib/lp/bugs/tests/testfiles/broken_bug_li_item\.xml|
            lib/lp/bugs/tests/testfiles/unescaped_control_character.xml
          )$
    -   id: check-yaml
    -   id: debug-statements
        exclude: systemdocs\.py
    -   id: file-contents-sorter
        files: ^\.codespell-ignore
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, db-devel]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--keep-percent-format, --py38-plus]
        exclude: |
          (?x)^(
            lib/contrib/.*
            |utilities/community-contributions\.py
          )$
-   repo: https://github.com/psf/black-pre-commit-mirror
    # Update the pinned version of black below used by
    # blackdoc when updating this version.
    rev: 23.10.1
    hooks:
      - id: black
        exclude: |
          (?x)^(
            lib/contrib/.*
            |utilities/community-contributions\.py
          )$
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort
        args: [--profile, black]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        exclude: ^lib/contrib/
        additional_dependencies:
          - flake8-absolute-import==1.0.0.1
          - flake8-alfred==1.1.1
          - flake8-bugbear==23.3.12
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.53.0
    hooks:
    -   id: eslint
        args: [--quiet]
        # 20.7.0 upgraded from npm 9.8.1 to 10.1.0, which appears to fail to
        # use the proxy correctly in Launchpad CI builds.
        language_version: "20.6.1"
-   repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
    -   id: blackdoc
        args: ["-l", "78"]
        exclude: ^doc/.*
        additional_dependencies:
          # Update this pinned version too when updating the black pre-commit
          # hook's version above.
          - black==23.10.1
-   repo: https://git.launchpad.net/lp-lint-doctest
    rev: '0.5'
    hooks:
    -   id: lp-lint-doctest
        args: [--allow-option-flag, IGNORE_EXCEPTION_MODULE_IN_PYTHON2]
        exclude: ^doc/.*
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
    -   id: shellcheck
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        args: ["-I", ".codespell-ignore"]
        files: ^(.*\.js|.*\.rst)$
        exclude: |
          (?x)^(
            # URL-encoding of "foö".
            lib/lp/bugs/doc/bugattachments\.rst
            # Quoted-printable encoding.
            |lib/lp/code/doc/branch-notifications\.rst
            # Word truncated by stemming.
            |lib/lp/services/database/doc/textsearching\.rst
          )$
-   repo: https://github.com/get-woke/woke
    rev: v0.19.0
    hooks:
    -   id: woke-from-source
        files: ^doc/.*\.rst$
