# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-json
        exclude: |
          (?x)^(
            lib/lp/services/sitesearch/tests/data/bingsearchservice-incomplete-response\.json
          )$
    -   id: check-xml
        exclude: |
          (?x)^(
            lib/lp/bugs/tests/testfiles/broken_bug_li_item\.xml|
            lib/lp/bugs/tests/testfiles/unescaped_control_character.xml
          )$
    -   id: check-yaml
    -   id: debug-statements
        exclude: systemdocs\.py
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, db-devel]
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: ^lib/contrib/
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--keep-percent-format]
        exclude: ^lib/contrib/
    -   id: pyupgrade
        alias: pyupgrade-py3
        name: pyupgrade (--py3-plus)
        args: [--keep-percent-format, --py3-plus]
        files: |
          (?x)^lib/lp/(
            answers
            |app
            |archivepublisher
            |archiveuploader
            |blueprints
            |bugs
            |buildmaster
            |charms
            |code
            |codehosting
            |coop
            |oci
            |registry
            |scripts
            |services
            |snappy
            |soyuz
            |testing
            |testopenid
            |tests
            |translations/(browser|interfaces|model)
          )/
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v4.2.0
    hooks:
    -   id: eslint
        args: [--quiet]
-   repo: https://git.launchpad.net/lp-lint-doctest
    rev: '0.3'
    hooks:
    -   id: lp-lint-doctest
        args: [--allow-option-flag, IGNORE_EXCEPTION_MODULE_IN_PYTHON2]
        exclude: ^doc/.*|.*/testfiles/.*|bingsearchservice-mapping\.txt
