options:
  domain:
    type: string
    description: Domain name for this instance.
    default: "launchpad.test"
  domain_librarian:
    type: string
    description: Domain name for this instance's librarian service.
    default: "launchpadlibrarian.test"
  enable_media:
    type: boolean
    description: Whether to enable the "media" domain.
    default: false
  google_site_verification:
    type: string
    description: >
      If set, serve a /google{...} URL that can be used to verify domain
      ownership.
    default: ""
  redirect_edge:
    type: boolean
    description: Whether to include redirections for legacy "edge" domains.
    default: false
  redirect_features:
    type: boolean
    description: >
      Whether to include redirections for legacy "features" and "blueprint"
      domains.
    default: false
  redirect_librarian:
    type: boolean
    description: >
      Whether to include redirections for the legacy "librarian" domain.
    default: false
  ssl_chain_required:
    type: boolean
    description: >
      Whether an intermediate certificate chain is needed for this service.
      In development, we use self-signed certificates which don't have a
      certificate chain; but in real deployments, we need to send a
      certificate chain.
    default: false
  webmaster_email:
    type: string
    description: Webmaster contact address.
    default: "webmaster@launchpad.test"
