options:
  active:
    type: boolean
    default: true
    description: If true, enable jobs that may change the database.
  domain_ftpmaster:
    type: string
    description: Domain name for the published Ubuntu archive.
    default: "archive.ubuntu.test"
  rsync_secrets:
    type: string
    description: Secrets for rsync
    default: ""
  signing_client_private_key:
    type: string
    description: Private key for encrypting communication between client and signing service. 
    default: ""
  signing_client_public_key:
    type: string
    description: Public key for encrypting communication between client and signing service. 
    default: ""
  signing_endpoint:
    type: string
    description: Endpoint for the signing service. 
    default: ""
  webmaster_email:
    type: string
    description: Webmaster contact address.
    default: "webmaster@launchpad.test"
  ubuntu_auth_users:
    type: string
    description: Authenticated users for rsync ubuntu
    default: ""
  ubuntu_dists_hosts_allow:
    type: string
    description: IP addresses permitted to connect to ubuntu/dists.
    default: ""
  ubuntu_germinate_hosts_allow:
    type: string
    description: IP addresses permitted to connect to ubuntu-germinate.
    default: ""
  ubuntu_partner_auth_users:
    type: string
    description: Authenticated users for rsync ubuntu-partner
    default: ""