options:
  active:
    type: boolean
    default: true
    description: If true, enable jobs that may change the database.
  domain_derived_archive:
    type: string
    description: Domain name for this instance.
    default: "derived.archive.test"
  domain_test_rebuild:
    type: string
    description: Domain name for this instance.
    default: "rebuild-test.test"
  domain_test_rebuild_aliases:
    type: string
    default: "[]"
    description:
      A YAML-encoded list of aliases for the test rebuild's primary domain.
  signing_client_public_key:
    type: string
    description: Public key for encrypting communication between client and signing service. 
    default: ""
  signing_client_private_key:
    type: string
    description: Private key for encrypting communication between client and signing service. 
    default: ""
  signing_endpoint:
    type: string
    description: Endpoint for the signing service. 
    default: ""
