options:
  domain:
    type: string
    description: Domain name for this instance.
    default: "launchpad.test"
  port:
    type: int
    description: Port for the assets website.
    default: 8009
