options:
  active:
    type: boolean
    default: true
    description: If true, enable jobs that may change the database.
  logparser_max_parsed_lines:
    type: int
    default: 10000000
    description: > 
      The maximum number of lines that should be parsed by the launchpad log
      parser.
  oval_data_rsync_endpoint:
    type: string
    default:
    description: If set, use as rsync endpoint for synchronizing the OVAL data.
  require_signing_keys:
    type: boolean
    description: > 
      If true, PPAs and copy archives will only be published once their
      signing-keys have been generated.
    default: False
  signing_client_private_key:
    type: string
    description: >
      Private key for encrypting communication between client and signing
      service. 
    default: ""
  signing_client_public_key:
    type: string
    description: >
      Public key for encrypting communication between client and signing
      service. 
    default: ""
  signing_endpoint:
    type: string
    default:
    description: Endpoint for the signing service.
